### ISSUE TITLE
utf 8 for the Arabic language not work good in seo() 

### ISSUE THREAD

**Issue by fh32000** [ralphjsmit/laravel-seo#18]
this code using seo helper and simple $model->seo->title
```
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- SEO -->
    {!! seo() !!}
    <!-- End SEO -->


    <!-- simple title -->
    <title>{{$tool->seo->title}}</title>
    <!-- end title -->
```
this result

<img src="https://i.ibb.co/61MqMYB/ksnip.png" alt="ksnip" border="0">

**Comment by fh32000** [comment]
@tuimz @ralphjsmit @

**Comment by ralphjsmit** [comment]
Hey @fh32000, first of all, you don't need to output a `<title>` tag manually. The `{{ seo() }}` helper is enough, so you can remove the following code:

```blade
<!-- simple title -->
    <title>{{$tool->seo->title}}</title>
    <!-- end title -->
```

Next up, it looks like you added the SEO information to the variable `$tool`. I think you should update the code to the following:

```diff
- {!! seo() !!}
+ {!! seo($tool) !}}
```

Let me know if that works!

**Comment by fh32000** [comment]
it work for me with  flowing step  
In Model
```
public function getDynamicSEOData(): SEOData
    {
        return new SEOData(
            title: "$this->name | خدمات سريعه اون لاين",
            description: $this->intro_excerpt,
            author: $this->author->name,
            url: "/tools/$this->slug",
        );
    }
```
In Controller

```
return view('tools', ['tool' => $tool, 'SEOData' => $tool->getDynamicSEOData()]);
```

in view 
```
   <!-- SEO -->
    {!! seo($SEOData??null) !!}
   <!-- End SEO -->
```

**Comment by ralphjsmit** [comment]
Awesome!

Does it also work if you update the controller to this:

```php
return view('tools', ['tool' => $tool]);
```

And the view to this:

```blade
{!! seo($tool ?? null) !!}
```

That should work as well.

**Comment by fh32000** [comment]
no the text in Arabic will broke

**Comment by ralphjsmit** [comment]
Could you perhaps explain what exactly breaks? I've never really used UTF-8 stuff, and neither am I very aware of the consequences. Do you mean that you input arabic text and that it outputs these `% D9%` characters?

**Comment by aeq-dev** [comment]
Hi @fh32000 
I have arabic posts and it works fine, may be you should check you browser or css files

**Comment by fh32000** [comment]
@ralphjsmit  yse the input Arabic text  outputs these % D9% characters 
when i use 
 {!! seo() !!}
 but work find with getDynamicSEOData
 and 
 {!! seo($SEOData??null) !!}

**Comment by ralphjsmit** [comment]
@fh32000 I just checked whether I can reproduce it by outputting some random Arabic text. For me it does work, so I actually have no idea why it doesn't work for you:

<img width="1174" alt="Schermafbeelding 2022-10-06 om 18 53 42" src="https://user-images.githubusercontent.com/59207045/194372975-19b49eb4-52ec-4fc9-ba9e-36badeee3c72.png">

Perhaps it could be caused by something like this: https://stackoverflow.com/questions/44728089/incorrect-rendering-of-language-e-g-arabic.

Otherwise, I'd just suggest to use the solution like `{!! seo($SEOData??null) !!}`, because otherwise it looks like it's something in your installation.

Thanks!
