### ISSUE TITLE
Name spacing for Modifying tags before they're sent

### ISSUE THREAD

**Issue by eugenevdm** [ralphjsmit/laravel-seo#22]
I'm struggling with the name spacing example in the readme file:

https://github.com/ralphjsmit/laravel-seo#modifying-tags-before-they-are-rendered

```php
SEOManager::tagTransformer(function (TagCollection $tags): TagCollection {
    $tags = $tags->reject(fn(Tag $tag) => $tag instanceof OpenGraphTag);
    
    $tags->push(new MetaTag(name: 'custom-tag', content: 'My custom content'));
    // Will render: <meta name="custom-tag" content="My custom content">
    
    return $tags;
});
```

The error is:

```
TypeError
App\Http\Controllers\PostController::App\Http\Controllers\{closure}(): Argument #1 ($tag) must be of type App\Models\Tag, RalphJSmit\Laravel\SEO\Tags\RobotsTag given
```

The only one that sort of seems okay so far is this one:

```
use RalphJSmit\Laravel\SEO\Facades\SEOManager;
```

Any clues what other name spaces to use? I tried automatic importing in Visual Studio code but ended up with the above error.

**Comment by ralphjsmit** [comment]
Hey Eugene, with the namespaces, you should only import names that start with `RalphJSmit\Laravel\SEO`.

So I think you should have:

```
use RalphJSmit\Laravel\SEO\Facades\SEOManager;
use RalphJSmit\Laravel\SEO\TagCollection;
use RalphJSmit\Laravel\SEO\Support\Tag;
use RalphJSmit\Laravel\SEO\Support\OpenGraphTag;
use RalphJSmit\Laravel\SEO\Support\MetaTag;
```

The issue with the error is that you imported `App\Models\Tag`. That model is a class in your project directory. The package doesn't know that this model exists, because everyone is free to create it's own models. That's why every import should start with `RalphJSmit\Laravel\SEO`, because that are only the files that exist.

Let me know if that works!
