### ISSUE TITLE
Can you release a version that works with php7.*

### ISSUE THREAD

**Issue by hexxondiv** [ralphjsmit/laravel-seo#27]
Thanks for your great package.
Can you release a version that works with php7.*

**Comment by ralphjsmit** [comment]
Hey! Thank you  😊

Off the top of my head I think the package depends on certain PHP 8.0+ features, so I'm not sure it it's possible to make it work on PHP 7.x. To be honest I'm not very keen on reworking lots of code just to make it work on PHP 7 (which is completely deprecated). If you can do it work minimal changes, you can provide a PR. Otherwise I'm afraid the package will only stay working PHP 8.0+
