### ISSUE TITLE
Canonical URL override

### ISSUE THREAD

**Issue by richdynamix** [ralphjsmit/laravel-seo#33]
Is it possible to override the canonical URL on a page by page basis, rather than only setting in the global config?

It is often required to manually set a canonical url for content that has been syndicated from multiple sources, such as news aggregator sites.

**Comment by ralphjsmit** [comment]
@richdynamix You can use the `$SEOData->url`, that url is used to create a canonical url. If you are open to it, you can create a PR that adds a `?string $canonicalUrl` property to the `SEOData` object. If that `$canonicalUrl` is set, then it will use that url for the canonical, otherwise it would use the regular `$url` property.
