### ISSUE TITLE
Allow for `<title>` and `og:title` to be different

### ISSUE THREAD

**Issue by Voltra** [ralphjsmit/laravel-seo#53]
Currently, there's only one `title` field in `SEO`. Often, for SEO and/or UX purposes, the page title and the `og:title` are different. This is impossible or tedious to do using the package in its current state.

It'd be nice to have an `og_title` database column that defaults to the value of `title`.

**Comment by Voltra** [comment]
Hotfix usable for now:

```php
SEOManager::tagTransformer(function (TagCollection $tags): TagCollection {
    $tags = $tags->reject(fn ($tag) => $tag instanceof TitleTag);

    // [...]

    return $tags;
});
```

And then format the title tag in the layout using `{{ $myTitle }}{{ config('seo.title.title_suffix') }}`

**Comment by ralphjsmit** [comment]
Thanks for your request! I see, it can indeed make sense to allow setting a different `og:title` (but default to the normal title). 
I too busy right now to implement it, but if you can create a PR yourself, then I'm more than happy to merge it. 

It's not too difficult, you can add a property to the `SEOData` called `public ?string $openGraphTitle = null`. Then, in the `OpenGraphTags` class you can check for `$SEOData->openGraphTitle ?? $SEOData->title` instead of only `$SEOData->title`.
