### ISSUE TITLE
How to turn the seo into json?

### ISSUE THREAD

**Issue by misbahansori** [ralphjsmit/laravel-seo#57]
Hi, thank you for the work you've put into developing and maintaining this repo.
I recently have a situation where I needed to retrieve SEO information from an endpoint.
I want to return my seo as json, but right now it is just returns a raw data from database
```
class PostResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'id'             => $this->id,
            'slug'           => $this->slug,
            'title'          => $this->title,
            'excerpt'        => $this->excerpt,
            'content'        => $this->content,
            'seo'            => $this->seo,  // <-- Here...
            'featured_image' => $this->featuredImage,
            'published_at'   => $this->published_at,
            'created_at'     => $this->created_at,
        ];
    }
}

```
and it returns something like this :
```
"seo": {
    "id": 2,
    "model_type": "post",
    "model_id": 1,
    "description": "Commodi elit in deb",
    "title": "In vitae rerum quis ",
    "image": null,
    "author": "Leah Mcclain",
    "robots": null,
    "canonical_url": null,
    "created_at": "2023-12-30T09:55:45.000000Z",
    "updated_at": "2023-12-30T09:55:45.000000Z"
},
```
I was wondering if it could be enhanced to provide more useful information in a JSON format

**Comment by ralphjsmit** [comment]
Hi there! Thanks for your question.
It depends a bit on what format/output you are looking for and what is the use. In short, the `$this->seo` Model is the basis for a so-called `$SEOData = new SEOData()` object. This `SEOData` object is the basis for all the tags that are generated in the actual HTML.

For example, you can get the generated tags like this:

```php
'seoTags' => app(TagManager::class)->for($this->seo->prepareForUsage())->tags,
```

However, that will just be a collection of specialist Tag objects. For example, you can map these tags so that you get the all the necessary data to generate the HTML:

```
'seoTags' => app(TagManager::class)->for($this->seo->prepareForUsage())->tags->mapWithKeys(fn (Tag $tag) => [
    'tag' => $tag->tag,
    'attributes' => $tag->collectAttributes(),
    'inner' => $tag->inner ?? null,
]);
```

This will generate an array of arrays with info about the tags. For example, if the following tag needs to be rendered:

```html
<meta name="robots" content="max-snippet:-1,max-image-preview:large,max-video-preview:-1">
```

Then the output of the `seoTags` property will be like this:

```php
'seoTags' => [
   [
      'tag' => 'meta',
      'attributes' => [
           'name' => 'robots',
           'content' => 'max-snippet:-1,max-image-preview:large,max-video-preview:-1',
      ],
      'inner' => null, // In case any HTML is needed INSIDE the `<meta>` tag, then this will contain that HTML.
   ],
   // ...
],
```

Hope this helps!
