### ISSUE TITLE
[Bug] The package added prefix in the titel

### ISSUE THREAD

**Issue by chengkangzai** [ralphjsmit/laravel-seo#61]
```html
<title>&lt;!--[if BLOCK]&gt;&lt;![endif]--&gt;The Qing | Kuala Lumpur | Pixalink Explore</title>
```

Hi @ralphjsmit , have been using this package for a long time but from time to time the packages acts weirdly by adding extra "IF BLOCK" to the title and the html tag 

I am using exactly `versions : * 1.4.3` which is the latest version. 
This bug have been causing a big problem to me personally, as you can see at [Pixalink Explore](https://explore.pixalink.io/). 
I have screenshot it for your references. 
![Screenshot 2024-01-30 at 1 49 38 AM](https://github.com/ralphjsmit/laravel-seo/assets/43839286/93f2323a-9efe-4316-b321-334539034a1e)

here's the config 
```php
return [
    'model' => SEO::class,

    'site_name' => config('app.name'),

    'sitemap' => '/sitemap.xml',

    'canonical_link' => true,

    'robots' => [
        'default' => 'max-snippet:-1,max-image-preview:large,max-video-preview:-1',

        'force_default' => false,
    ],

    'favicon' => '/icons/Pixalink-Logo-N-150x150.png',

    'title' => [
        'infer_title_from_url' => true,
        'suffix' => ' | '.config('app.name'),
        
        'homepage_title' => config('app.name'),
    ],

    'description' => [
        'fallback' => 'omitted.',
    ],

    'image' => [
        'fallback' => '/Pixalink Full Logo 16-9.webp',
    ],

    'author' => [
        'fallback' => 'Pixalink.io',
    ],

    'twitter' => [
        '@username' => null,
    ],
];

```

Thanks in advance

**Comment by thehands79** [comment]
php 8.2.15
laravel/framework 10.43.0
ralphjsmit/laravel-seo 1.4.3

I also see this behaviour, although strangely not locally but when I deploy to server environments.

**Comment by chengkangzai** [comment]
Try to clear all the cache from Laravel, restart PHP-FPM, clear OPCACHE if u enabled and see if it works... My PROD get it solve by this by now my staging having this issues 😔

Best Regards,
Ching Cheng Kang
________________________________

**Comment by thehands79** [comment]
It's not pretty but it's a quick workaround. I'm not convinced this package is being maintained any longer.
```
@php
$seo = seo();
$pattern = '<title><!--[if BLOCK]><![endif]-->';
$replacement = '<title>';
$seo = str_replace($pattern, $replacement, $seo);
@endphp
{!! $seo !!}
```

**Comment by chengkangzai** [comment]
Let's tag @ralphjsmit out for this....

I personally contacted him when I created this issues and he replied so I believe he's still actively maintain it..?

Not sure if we should open a PR that change the source code to get this dirty fix merged....

**Comment by ralphjsmit** [comment]
Hi guys, thanks for your input! The package is definitely being maintained, but I also just have my normal work to do, maintain paid packages and I also went to Laracon this week.

Anyway, these block if-conditions are comments that Livewire automatically adds so-called Morph Markers around `@if` conditions in your code. Likely, your Layout file is therefore also in some way parsed by Livewire.

The easy fix would have been to (temporarily) [disable morph markers](https://livewire.laravel.com/docs/morphing#injecting-morph-markers) in your code. However, I think that should not be necessary, since I just made a change that updated the template to not use `@foreach`/`@if` anymore, but just plain PHP `<?php foreach (...) : ?>` statements. 

Can you try version 1.4.4 and let me know whether that works?

**Comment by chengkangzai** [comment]
hi @ralphjsmit  it works on my local! thanks!!!

**Comment by ralphjsmit** [comment]
Great, thanks for letting me know! Then I will close the issue.
