### ISSUE TITLE
getDynamicSEOData(): tags and section don't generate anything

### ISSUE THREAD

**Issue by thehands79** [ralphjsmit/laravel-seo#62]
php 8.2.15
laravel/framework 10.43.0
ralphjsmit/laravel-seo 1.4.3

```
public function getDynamicSEOData(): SEOData
    {
        Log::debug($this->category->name); // content in logs
        Log::debug($this->tags->pluck('name')->toArray()); // content in logs

        return new SEOData(
            title: $this->title,
            description: Str::words($this->description, 30, ''),
            author: $this->user->name,
            section: $this->category->name, // no content in page
            tags: $this->tags->pluck('name')->toArray(), // no content in page
            schema: SchemaCollection::initialize()->addArticle(),
        );
    }
```

**Comment by ralphjsmit** [comment]
Hi @thehands79! Do you echo the Eloquent model in your Blade as well? Like `{!! seo($model !!}`?

**Comment by ralphjsmit** [comment]
Hi, thank you! I checked and the `tags` and `section` properties are only outputted when `$SEOData->type === 'article`. The default type is "website", but you can set it to article or other types for specific pages. The tags and section are only relevant for the OpenGraph article output and therefore not included. You can view the [source code](https://github.com/ralphjsmit/laravel-seo/blob/2856dd04fbf9b73df9b85c3bd08267a9d9fc4ceb/src/Tags/OpenGraphTags.php#L62) here.

In order to fix it, you can update the type to article:

```php
        return new SEOData(
            type: 'article',
            // ..
        );
    }
```

**Comment by thehands79** [comment]
HI, thanks for the reply. It would be better if the README was explicit about which properties are available for which types (or did I miss that?). You could add a `<table>` with props as rows and types as columns.

**Comment by ralphjsmit** [comment]
Thanks for the idea! The docs already do say it, but it's not super-explicit:

<img width="772" alt="Scherm­afbeelding 2024-02-08 om 15 09 47" src="https://github.com/ralphjsmit/laravel-seo/assets/59207045/71893c6d-ad9e-4fbf-ab76-17c7aa4ce15a">

I'm now a bit too busy to create a (Markdown) table, but if you have time, then you can definitely PR it 👍
