### ISSUE TITLE
Can we have Product schema ?

### ISSUE THREAD

**Issue by ariaieboy** [ralphjsmit/laravel-seo#8]
hello @ralphjsmit 
thanks for your great package 
can u please add the [product ](https://developers.google.com/search/docs/advanced/structured-data/product)schema ?

**Comment by ralphjsmit** [comment]
Hey @ariaieboy, thanks for your message!

Adding the Product schema is certainly possible. However, I'm currently extremely, so I'll unfortunately not be able to do so in the short term. 

As a temporary solution, you should be able to add the Product schema yourself, even without knowledge of package development. If you take a look at how the [ArticleSchema](https://github.com/ralphjsmit/laravel-seo/blob/main/src/Schema/ArticleSchema.php) and [BreadcrumbListSchema](https://github.com/ralphjsmit/laravel-seo/blob/main/src/Schema/BreadcrumbListSchema.php) are implemented, it shouldn't be very difficult. 

Perhaps I should focus on integrating the [Spatie Schema](https://github.com/spatie/schema-org), instead of having to manually add each schema. Spatie's package supports almost every schema, perhaps that's better. Integrating that shouldn't be too difficult.

**Comment by shahghasiadil** [comment]
@ralphjsmit I possible I should create this PR!
